# Generated by Django 4.2.20 on 2025-04-11 14:35

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("image", models.ImageField(upload_to=core.models.get_upload_path)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("tesseract_text", models.TextField(blank=True, null=True)),
                ("gemini_text", models.TextField(blank=True, null=True)),
                ("final_text", models.TextField(blank=True, null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
